package hobbytracker;

import java.sql.*;
import org.mindrot.jbcrypt.BCrypt;

/** Owns embedded H2 schema creation. Connections are short-lived and never shared between threads. */
public final class DatabaseManager {
    public static final String URL = "jdbc:h2:./questlog_db;AUTO_SERVER=TRUE";
    private DatabaseManager() { }
    public static Connection connection() throws SQLException { return DriverManager.getConnection(URL, "sa", ""); }
    public static void initialize() throws SQLException {
        try (Connection c = connection(); Statement s = c.createStatement()) {
            s.executeUpdate("CREATE TABLE IF NOT EXISTS users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, display_name VARCHAR(80) NOT NULL, email VARCHAR(254) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, level INT NOT NULL DEFAULT 5 CHECK(level >= 1), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS hobbies (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, title VARCHAR(120) NOT NULL, description VARCHAR(1000), status VARCHAR(12) NOT NULL CHECK(status IN ('ACTIVE','PAUSED','COMPLETED')), progress_percentage INT NOT NULL DEFAULT 0 CHECK(progress_percentage BETWEEN 0 AND 100), streak_days INT NOT NULL DEFAULT 0 CHECK(streak_days >= 0), CONSTRAINT fk_hobby_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS activity_logs (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, action_title VARCHAR(120) NOT NULL, action_description VARCHAR(1000), timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_log_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE)");
            s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_hobbies_user_status ON hobbies(user_id, status)");
            s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_logs_user_time ON activity_logs(user_id, timestamp DESC)");
            try (ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM users")) { rs.next(); if (rs.getLong(1) == 0) createDefault(c); }
        }
    }
    private static void createDefault(Connection c) throws SQLException {
        try (PreparedStatement p = c.prepareStatement("INSERT INTO users(display_name,email,password_hash) VALUES(?,?,?)")) {
            p.setString(1, "Adventurer"); p.setString(2, "adventurer@questlog.local");
            p.setString(3, BCrypt.hashpw("questlog", BCrypt.gensalt())); p.executeUpdate();
        }
    }
}
