package hobbytracker;

import animatefx.animation.FadeIn;
import java.util.Optional;
import java.util.concurrent.*;
import javafx.animation.*;
import javafx.application.Platform;
import javafx.geometry.*;
import javafx.scene.*;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.Stage;
import javafx.util.Duration;

/** One-card login/registration controller with in-card form transitions. */
public final class HobbyTrackerLogin {
    private final HobbyTracker application; private final Executor executor;
    private final StackPane formHost=new StackPane(); private final Label message=new Label(); private final ProgressIndicator spinner=new ProgressIndicator();
    private VBox loginForm, signUpForm; private TextField loginEmail, signUpName, signUpEmail; private PasswordField loginPassword, signUpPassword; private boolean transitioning;
    public HobbyTrackerLogin(HobbyTracker application, Executor executor){this.application=application;this.executor=executor;}
    public void show(Stage stage){loginForm=loginForm(stage);signUpForm=signUpForm(stage);signUpForm.setVisible(false);formHost.getChildren().addAll(loginForm,signUpForm);formHost.setMinHeight(245);message.getStyleClass().add("form-hint");message.setWrapText(true);spinner.setMaxSize(18,18);spinner.setVisible(false);VBox card=new VBox(14,HobbyTracker.createLogo(118),title("Welcome back"),muted("Pick up your next side quest."),formHost,new HBox(8,spinner,message));card.setAlignment(Pos.CENTER);card.setPadding(new Insets(38));card.setMaxWidth(390);card.setMinHeight(560);card.setStyle("-fx-background-color: #131A2B;");card.getStyleClass().addAll("questlog-card","login-card");StackPane root=new StackPane(card);root.setPadding(new Insets(28));root.getStyleClass().add("questlog-root");Scene scene=new Scene(root,900,650);HobbyTracker.applyStyle(scene);stage.setMinWidth(520);stage.setMinHeight(500);stage.setScene(scene);stage.show();new FadeIn(card).setSpeed(1.4).play();loginEmail.requestFocus();}
    private VBox loginForm(Stage stage){loginEmail=new TextField();loginEmail.setPromptText("Email");loginPassword=new PasswordField();loginPassword.setPromptText("Password");Button login=primary("LOGIN"),google=secondary("SIGN IN WITH GOOGLE"),link=link("Don't have an account? Sign Up");login.setOnAction(e->login(stage,login));loginPassword.setOnAction(e->login.fire());google.setOnAction(e->google(stage,google));link.setOnAction(e->swap(loginForm,signUpForm));return form(loginEmail,loginPassword,login,google,link);}
    private VBox signUpForm(Stage stage){signUpName=new TextField();signUpName.setPromptText("Display name");signUpEmail=new TextField();signUpEmail.setPromptText("Email");signUpPassword=new PasswordField();signUpPassword.setPromptText("Password (8+ characters)");Button create=primary("CREATE ACCOUNT"),google=secondary("SIGN UP WITH GOOGLE"),link=link("Already have an account? Log In");create.setOnAction(e->register(stage,create));signUpPassword.setOnAction(e->create.fire());google.setOnAction(e->google(stage,google));link.setOnAction(e->swap(signUpForm,loginForm));return form(signUpName,signUpEmail,signUpPassword,create,google,link);}
    private VBox form(Node... nodes){VBox v=new VBox(10,nodes);v.setAlignment(Pos.CENTER);v.setMaxWidth(Double.MAX_VALUE);return v;}
    private void swap(VBox from,VBox to){if(transitioning)return;transitioning=true;setLinksDisabled(true);FadeTransition out=new FadeTransition(Duration.millis(150),from);TranslateTransition slideOut=new TranslateTransition(Duration.millis(150),from);slideOut.setByX(-16);ParallelTransition leave=new ParallelTransition(out,slideOut);out.setToValue(0);leave.setOnFinished(e->{from.setVisible(false);from.setOpacity(1);from.setTranslateX(0);to.setOpacity(0);to.setTranslateX(16);to.setVisible(true);FadeTransition in=new FadeTransition(Duration.millis(180),to);TranslateTransition slideIn=new TranslateTransition(Duration.millis(180),to);slideIn.setToX(0);in.setToValue(1);ParallelTransition enter=new ParallelTransition(in,slideIn);enter.setOnFinished(done->{transitioning=false;setLinksDisabled(false);if(to==loginForm)loginEmail.requestFocus();else signUpName.requestFocus();});enter.play();});leave.play();}
    private void login(Stage stage,Button button){String email=loginEmail.getText().trim(),password=loginPassword.getText();if(email.isBlank()||password.isBlank()){showMessage("Enter your email and password.",false);return;}busy(button,true,"Signing in...");CompletableFuture.supplyAsync(()->{try{return new AuthService().login(email,password);}catch(Exception e){throw new CompletionException(e);}},executor).whenComplete((user,error)->Platform.runLater(()->{busy(button,false,null);if(error!=null){showMessage("Could not sign in. Please try again.",false);return;}if(user.isEmpty()){showMessage("Invalid email or password.",false);return;}openApp(stage,user.get());}));}
    private void register(Stage stage,Button button){String name=signUpName.getText().trim(),email=signUpEmail.getText().trim(),password=signUpPassword.getText();if(name.isBlank()){showMessage("Display name is required.",false);return;}if(!email.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")){showMessage("Enter a valid email address.",false);return;}if(password.length()<8){showMessage("Password must be at least 8 characters.",false);return;}busy(button,true,"Creating account...");CompletableFuture.supplyAsync(()->{try{return new AuthService().register(name,email,password);}catch(Exception e){throw new CompletionException(e);}},executor).whenComplete((user,error)->Platform.runLater(()->{busy(button,false,null);if(error!=null){showMessage(root(error).getMessage(),false);return;}SessionManager.getInstance().logout();loginEmail.setText(email);loginPassword.clear();showMessage("Account created successfully! Please log in.",true);swap(signUpForm,loginForm);}));}
    private void google(Stage stage,Button button){busy(button,true,"Opening Google in your browser...");CompletableFuture.supplyAsync(()->{try{GoogleOAuthService.GoogleProfile p=new GoogleOAuthService().signIn();return new AuthService().loginGoogle(p.displayName(),p.email());}catch(Exception e){throw new CompletionException(e);}},executor).whenComplete((user,error)->Platform.runLater(()->{busy(button,false,null);if(error!=null){showMessage(root(error).getMessage(),false);return;}openApp(stage,user);}));}
    private void openApp(Stage stage,User user){SessionManager.getInstance().login(user);new HobbyTrackerPcUi(application).show(stage);}
    private void busy(Button source,boolean on,String text){source.setDisable(on);spinner.setVisible(on);if(text!=null)showMessage(text,true);}
    private void showMessage(String text,boolean positive){message.setText(text==null?"":text);message.setStyle(positive?"-fx-text-fill: #00E676;":"-fx-text-fill: #FF8A80;");}
    private void setLinksDisabled(boolean disabled){loginForm.getChildren().forEach(n->{if(n instanceof Button b&&b.getText().contains("account"))b.setDisable(disabled);});signUpForm.getChildren().forEach(n->{if(n instanceof Button b&&b.getText().contains("account?"))b.setDisable(disabled);});}
    private Label title(String text){Label l=new Label(text);l.getStyleClass().add("login-title");return l;}private Label muted(String text){Label l=new Label(text);l.getStyleClass().add("muted-text");return l;}private Button primary(String text){Button b=new Button(text);b.setMaxWidth(Double.MAX_VALUE);b.getStyleClass().add("questlog-button-primary");return b;}private Button secondary(String text){Button b=new Button(text);b.setMaxWidth(Double.MAX_VALUE);b.getStyleClass().add("questlog-button-secondary");return b;}private Button link(String text){Button b=new Button(text);b.getStyleClass().add("quiet-button");return b;}private Throwable root(Throwable t){while(t.getCause()!=null)t=t.getCause();return t;}
}
