package hobbytracker;

import animatefx.animation.FadeIn;
import java.nio.file.*; import java.util.*; import java.util.concurrent.*;
import javafx.application.Platform; import javafx.geometry.*; import javafx.scene.*; import javafx.scene.control.*; import javafx.scene.layout.*; import javafx.stage.Stage;

/** The original desktop UI, with each view populated by the H2 DAO. */
public class HobbyTrackerPcUi {
 private final HobbyTracker app; private final StackPane host=new StackPane(); private final VBox navs=new VBox(6); private final QuestDao dao=new QuestDao(); private final ExecutorService io=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"questlog-db");t.setDaemon(true);return t;}); private Stage stage; private String view="Dashboard";
 public HobbyTrackerPcUi(HobbyTracker app){this.app=app;} public HobbyTrackerPcUi(HobbyTracker app,String ignored){this(app);}
 public void show(Stage s){stage=s;BorderPane root=new BorderPane();root.getStyleClass().add("questlog-root");root.setTop(header());root.setLeft(sidebar());root.setCenter(host);Scene scene=new Scene(root,1180,760);HobbyTracker.applyStyle(scene);s.setScene(scene);s.setMinWidth(850);s.setMinHeight(600);s.show();open("Dashboard");}
 private User me(){return SessionManager.currentUser().orElseThrow();}
 private Node header(){Label brand=new Label("QUESTLOG");brand.getStyleClass().add("brand-title");Label cap=new Label("CONTROL CENTER");cap.getStyleClass().add("header-caption");Region gap=new Region();HBox.setHgrow(gap,Priority.ALWAYS);Button mobile=new Button("OPEN MOBILE VIEW");mobile.getStyleClass().add("quiet-button");mobile.setOnAction(e->new HobbyTrackerMobileUi(app).show());HBox box=new HBox(16,new VBox(1,brand,cap),gap,badge("● ACTIVE","status-active"),mobile,new Button(me().displayName()));box.setAlignment(Pos.CENTER_LEFT);box.setPadding(new Insets(16,24,16,24));box.getStyleClass().add("top-header");return box;}
 private Node sidebar(){for(String n:List.of("Dashboard","Quests","Stats","Settings","Profile"))navs.getChildren().add(nav(n));Region g=new Region();VBox.setVgrow(g,Priority.ALWAYS);Button out=new Button("Sign out");out.getStyleClass().add("sidebar-signout");out.setOnAction(e->run(()->{new AuthService().logout(me());return null;},x->app.showLogin(stage)));VBox box=new VBox(14,new Label("YOUR QUESTS"),navs,g,out);box.setPadding(new Insets(24,14,20,14));box.setPrefWidth(205);box.getStyleClass().add("questlog-sidebar");return box;}
 private Button nav(String n){Button b=new Button(n);b.setMaxWidth(Double.MAX_VALUE);b.getStyleClass().add("questlog-nav-item");b.setOnAction(e->open(n));return b;}
 private void open(String n){view=n;navs.getChildren().forEach(x->{Button b=(Button)x;b.getStyleClass().remove("questlog-nav-item-active");if(b.getText().equals(n))b.getStyleClass().add("questlog-nav-item-active");});switch(n){case "Quests"->run(()->dao.hobbies(me().id(),false),this::quests);case "Stats"->run(()->new Object[]{dao.metrics(me().id()),dao.weeklyActivity(me().id())},this::stats);case "Settings"->settings();case "Profile"->profile();default->run(()->new Object[]{dao.metrics(me().id()),dao.hobbies(me().id(),true),dao.recent(me().id(),6)},this::dashboard);}}
 private <T> void run(Callable<T> c,java.util.function.Consumer<T> done){host.getChildren().setAll(new ProgressIndicator());CompletableFuture.supplyAsync(()->{try{return c.call();}catch(Exception e){throw new CompletionException(e);}},io).whenComplete((v,e)->Platform.runLater(()->{if(e!=null){alert(Alert.AlertType.ERROR,"Database error",root(e).getMessage());return;}done.accept(v);}));}
 private void replace(Node n){host.getChildren().setAll(n);new FadeIn(n).setSpeed(1.7).play();}
 private void dashboard(Object[] x){QuestDao.Metrics m=(QuestDao.Metrics)x[0];@SuppressWarnings("unchecked")List<Hobby> hs=(List<Hobby>)x[1];@SuppressWarnings("unchecked")List<String[]> logs=(List<String[]>)x[2];FlowPane hcards=new FlowPane(14,14);hs.forEach(h->hcards.getChildren().add(hobbyCard(h)));VBox feed=new VBox(12);logs.forEach(a->feed.getChildren().add(activity(a[0],a[1],a[2])));if(logs.isEmpty())feed.getChildren().add(muted("No activity yet. Add a hobby to begin."));feed.getStyleClass().add("questlog-card");FlowPane metrics=new FlowPane(16,16,metric(String.format("%.0f%%",m.overall()),"Overall progress","hero-number"),metric(String.format("%02d",m.active()),"Active hobbies","stat-number"),metric(String.format("%02d",m.completed()),"Completed quests","stat-number"),metric(String.format("%02d",m.streak()),"Current streak","stat-number"));replace(scroll(new VBox(24,title("Welcome back, "+me().displayName(),"Here is how your personal quests are progressing."),section("Overall progress","Small wins add up."),metrics,section("Active hobby quests","Your current side quests"),hcards,section("Recent activity","Your latest progress"),new HBox(16,feed,actions(hs)))));}
 private void quests(List<Hobby> hs){VBox cards=new VBox(12);hs.forEach(h->cards.getChildren().add(hobbyCard(h)));replace(scroll(new VBox(20,title("Your hobby quests","Every hobby deserves a place in the log."),section("All quests","Active, paused and completed hobbies"),cards)));}
 private void stats(Object[] x){QuestDao.Metrics m=(QuestDao.Metrics)x[0];int[] w=(int[])x[1];VBox weekly=new VBox(12,section("Weekly momentum","Actions logged in the last seven days."));String[] days={"Mon","Tue","Wed","Thu","Fri","Sat","Sun"};for(int i=0;i<7;i++)weekly.getChildren().add(bar(days[i],w[i]));weekly.getStyleClass().add("questlog-card");replace(scroll(new VBox(20,title("Statistics","Your time and consistency at a glance."),new FlowPane(16,16,metric("—","Total hours logged*","stat-number"),metric(String.format("%02d",m.streak()),"Current streak","stat-number"),metric(String.format("%02d",m.completed()),"Quests completed","stat-number"),metric(String.format("%.0f%%",m.overall()),"Monthly consistency","hero-number")),weekly,muted("* No duration field exists. Add logged_minutes to activity_logs to calculate total hours."))));}
 private void settings(){Label note=muted("No temporary cache table exists; permanent data is never cleared.");Button backup=button("DATA BACKUP",false);backup.setOnAction(e->run(()->{Path dir=Paths.get("backups");Files.createDirectories(dir);Path f=dir.resolve("questlog-"+me().id()+"-"+System.currentTimeMillis()+".json");Files.writeString(f,dao.exportJson(me().id()));dao.log(me().id(),"Backup export","Exported data to "+f.toAbsolutePath());return f;},f->note.setText("Backup exported: "+f.toAbsolutePath())));Button clear=button("CLEAR CACHE",false);clear.setOnAction(e->note.setText("Nothing cleared: there are no disposable cache records."));VBox c=new VBox(15,new ToggleButton("Dark mode"),new CheckBox("Quest notifications"),new CheckBox("Enable mobile syncing"),new Separator(),backup,clear,note);c.getStyleClass().add("questlog-card");replace(scroll(new VBox(20,title("Settings","Keep Questlog feeling like yours."),c)));}
 private void profile(){User u=me();TextField name=new TextField(u.displayName()),email=new TextField(u.email());Label msg=muted("Level "+u.level()+" Hobbyist");Button save=button("SAVE PROFILE",true);save.setOnAction(e->{String n=name.getText().trim(),mail=email.getText().trim();if(n.isBlank()||!mail.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")){msg.setText("Enter a display name and valid email.");return;}run(()->{User changed=dao.updateUser(u.id(),n,mail);dao.log(u.id(),"Profile updated","Updated profile details.");return changed;},changed->{SessionManager.start(changed);msg.setText("Profile saved.");});});Button out=button("SIGN OUT",false);out.setOnAction(e->run(()->{new AuthService().logout(u);return null;},z->app.showLogin(stage)));VBox c=new VBox(13,new Label("LEVEL "+u.level()+" HOBBYIST"),new Label("Display name"),name,new Label("Email"),email,save,new Separator(),out,msg);c.getStyleClass().add("questlog-card");replace(scroll(new VBox(20,title("Your profile","The adventurer behind the quests."),c)));}
 private VBox actions(List<Hobby> hs){Button add=button("+ ADD HOBBY",true);add.setOnAction(e->add());Button upd=button("UPDATE PROGRESS",false);upd.setOnAction(e->{if(hs.isEmpty())alert(Alert.AlertType.INFORMATION,"Questlog","Add a hobby first.");else progress(hs.get(0));});Button done=button("COMPLETE QUEST",false);done.setOnAction(e->{if(!hs.isEmpty())complete(hs.get(0));});return card(new VBox(12,new Label("Today’s actions"),add,upd,done));}
 private VBox hobbyCard(Hobby h){Label name=new Label(h.title());name.getStyleClass().add("quest-name");Region gap=new Region();HBox.setHgrow(gap,Priority.ALWAYS);Button upd=button("UPDATE",false);upd.setOnAction(e->progress(h));Button done=button("COMPLETE",false);done.setDisable("COMPLETED".equals(h.status()));done.setOnAction(e->complete(h));return card(new VBox(10,new HBox(name,gap,badge(h.status(),"COMPLETED".equals(h.status())?"status-active":"status-pending")),muted((h.description()==null?"":h.description())+" · "+h.streakDays()+" day streak"),progressBar(h.progressPercentage()/100d),new HBox(muted(h.progressPercentage()+"% complete"),upd,done)));}
 private void add(){TextInputDialog d=new TextInputDialog();d.setTitle("Add hobby");d.setHeaderText("Start a new quest");d.setContentText("Hobby title:");d.showAndWait().map(String::trim).filter(s->!s.isBlank()).ifPresent(t->run(()->{dao.addHobby(me().id(),t,"");dao.log(me().id(),"Hobby created","Added "+t+".");return null;},z->open(view)));}
 private void progress(Hobby h){TextInputDialog d=new TextInputDialog(""+h.progressPercentage());d.setTitle("Update progress");d.setHeaderText(h.title());d.setContentText("Progress (0–100):");d.showAndWait().ifPresent(s->{try{int p=Integer.parseInt(s.trim());if(p<0||p>100)throw new NumberFormatException();run(()->{dao.updateProgress(h.id(),p);dao.log(me().id(),"Progress updated",h.title()+" is now "+p+"% complete.");return null;},z->open(view));}catch(NumberFormatException ex){alert(Alert.AlertType.WARNING,"Questlog","Progress must be a whole number from 0 to 100.");}});}
 private void complete(Hobby h){run(()->{dao.complete(h.id());dao.log(me().id(),"Quest completed",h.title()+" was completed.");return null;},z->open(view));}
 private VBox metric(String v,String l,String s){Label a=new Label(v);a.getStyleClass().add(s);return card(new VBox(7,a,muted(l)));}private HBox bar(String d,int n){Label l=new Label(d);l.setPrefWidth(38);ProgressBar p=progressBar(Math.min(1,n/5d));HBox.setHgrow(p,Priority.ALWAYS);return new HBox(10,l,p,new Label(""+n));}private VBox title(String h,String d){Label x=new Label(h);x.getStyleClass().add("page-greeting");return new VBox(4,x,muted(d));}private VBox section(String h,String d){Label x=new Label(h);x.getStyleClass().add("section-title");return new VBox(2,x,muted(d));}private VBox activity(String w,String h,String d){Label a=new Label(w);a.getStyleClass().add("timeline-time");Label b=new Label(h);b.getStyleClass().add("timeline-title");return new VBox(3,a,b,muted(d));}private VBox card(Node n){VBox b=new VBox(n);b.getStyleClass().add("questlog-card");return b;}private ScrollPane scroll(Node n){VBox w=new VBox(n);w.setPadding(new Insets(30));ScrollPane s=new ScrollPane(w);s.setFitToWidth(true);s.getStyleClass().add("content-scroll");return s;}private Button button(String t,boolean p){Button b=new Button(t);b.getStyleClass().add(p?"questlog-button-primary":"questlog-button-secondary");return b;}private Label muted(String t){Label l=new Label(t);l.getStyleClass().add("muted-text");return l;}private Label badge(String t,String s){Label l=new Label(t);l.getStyleClass().addAll("status-badge",s);return l;}private ProgressBar progressBar(double v){ProgressBar p=new ProgressBar(v);p.setMaxWidth(Double.MAX_VALUE);p.getStyleClass().add("questlog-progress");return p;}private void alert(Alert.AlertType t,String h,String m){Alert a=new Alert(t,m);a.setHeaderText(h);a.show();}private Throwable root(Throwable e){while(e.getCause()!=null)e=e.getCause();return e;}
}
