package hobbytracker;

import animatefx.animation.FadeIn;
import java.util.List;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.geometry.*;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.Stage;
import javafx.util.Duration;

/** UI-only desktop QUESTLOG. It intentionally has no DAO, session, auth, or persistence dependency. */
public final class HobbyTrackerPcUi {
    private final HobbyTracker app; private final ThemeManager theme=new ThemeManager(); private final StackPane host=new StackPane(); private final VBox navs=new VBox(6); private final BorderPane root=new BorderPane();
    private String view="Dashboard"; private Label timerLabel; private int seconds=25*60; private Timeline timer;
    private final List<Quest> quests=List.of(new Quest("🏃","Morning Jog","Jogging",.72,"ACTIVE"),new Quest("🏋","Strength Circuit","Gym",.45,"ACTIVE"),new Quest("📖","Atomic Habits","Reading",.86,"ACTIVE"),new Quest("✦","Mindful Mornings","Wellness",1,"DONE"));
    public HobbyTrackerPcUi(HobbyTracker app){this(app,"User");} public HobbyTrackerPcUi(HobbyTracker app,String ignored){this.app=app;}
    public void show(Stage stage){root.getStyleClass().addAll("questlog-root","desktop-root");theme.apply(root);root.setLeft(sidebar());root.setTop(header(stage));root.setCenter(host);Scene s=new Scene(root,1180,760);HobbyTracker.applyStyle(s);stage.setTitle("QUESTLOG — Desktop");stage.setMinWidth(930);stage.setMinHeight(620);stage.setScene(s);stage.show();open("Dashboard");}
    private Node sidebar(){Label brand=new Label("QUESTLOG");brand.getStyleClass().add("brand-title");Label cap=muted("YOUR PERSONAL QUEST BOARD");VBox top=new VBox(4,brand,cap);for(String[] n:new String[][]{{"⌂","Dashboard"},{"🏃","Jogging"},{"🏋","Gym"},{"📖","Reading"},{"♛","Ranks"},{"⚙","Settings"},{"◉","Profile"}})navs.getChildren().add(nav(n[0],n[1]));Region gap=new Region();VBox.setVgrow(gap,Priority.ALWAYS);Button out=secondary("⇥  SIGN OUT");out.getStyleClass().add("signout-button");out.setOnAction(e->out.setText("SIGNED OUT (DEMO)"));VBox box=new VBox(20,top,navs,gap,out);box.setPrefWidth(225);box.setPadding(new Insets(26,16,20,16));box.getStyleClass().add("desktop-sidebar");return box;}
    private Button nav(String icon,String name){Button b=new Button(icon+"   "+name);b.setMaxWidth(Double.MAX_VALUE);b.getStyleClass().add("desktop-nav-item");b.setOnAction(e->open(name));return b;}
    private Node header(Stage stage){Label hi=new Label("Welcome back, User");hi.getStyleClass().add("desktop-greeting");Label sub=muted("Ready to make progress?");Label streak=badge("🔥 12 DAY STREAK","status-active"),xp=badge("⭐ 2,450 XP","status-pending");Button toggle=secondary("◐ TOGGLE THEME");toggle.setOnAction(e->theme.setDark(!theme.isDark(),root));Button mobile=secondary("OPEN MOBILE VIEW");mobile.setOnAction(e->new HobbyTrackerMobileUi(app,"User").show(stage));Region gap=space();HBox h=new HBox(10,new VBox(2,hi,sub),gap,streak,xp,toggle,mobile);h.setAlignment(Pos.CENTER_LEFT);h.setPadding(new Insets(15,28,15,28));h.getStyleClass().add("top-header");return h;}
    private void open(String next){view=next;for(Node n:navs.getChildren()){Button b=(Button)n;b.getStyleClass().remove("desktop-nav-active");if(b.getText().endsWith(next))b.getStyleClass().add("desktop-nav-active");}Node content=switch(next){case "Jogging"->jogging();case "Gym"->gym();case "Reading"->reading();case "Ranks"->ranks();case "Settings"->settings();case "Profile"->profile();default->dashboard();};host.getChildren().setAll(content);new FadeIn(content).setSpeed(1.8).play();}
    private Node dashboard(){
        HBox metrics=new HBox(14,metric("78%","Overall progress","orange"),metric("03","Active quests","cyan"),metric("12","Completed quests","green"),metric("12 days","Current streak","purple"),metric("2,450","XP · Level 14","orange"));metrics.getChildren().forEach(n->{HBox.setHgrow(n,Priority.ALWAYS);if(n instanceof Region r)r.setMaxWidth(Double.MAX_VALUE);});
        VBox qlist=card(new VBox(12,section("Active quests","Your current side quests"),questRow(quests.get(0)),questRow(quests.get(1)),questRow(quests.get(2))));HBox.setHgrow(qlist,Priority.ALWAYS);
        VBox feed=card(new VBox(13,section("Recent activity","Small wins, logged"),activity("10 MIN AGO","🏃 Completed Morning Jog","+120 XP"),activity("YESTERDAY","🏋 Updated Gym Routine","+80 XP"),activity("FRI, 6:30 PM","📖 Finished Reading Session","+55 XP"),activity("THU, 9:10 PM","♛ Reached Gold Rank","Jogging")));feed.setPrefWidth(320);
        return scroll(new VBox(22,title("Dashboard","Your momentum at a glance."),metrics,new HBox(16,qlist,feed)));
    }
    private Node jogging(){
        VBox map=new VBox(new Label("MAP PLACEHOLDER\n\n       ● ───── ● ───── ●\n                  ╲\n                   ●"));map.setAlignment(Pos.CENTER);map.setMinHeight(355);map.getStyleClass().add("desktop-map");HBox.setHgrow(map,Priority.ALWAYS);
        ToggleGroup g=new ToggleGroup();ToggleButton metres=chip("Meters",g),miles=chip("Miles",g);metres.setSelected(true);Button start=primary("START RUN"),pause=secondary("PAUSE"),stop=secondary("STOP"),reset=secondary("RESET");Label state=muted("Ready to run");start.setOnAction(e->state.setText("Run in progress (demo)"));pause.setOnAction(e->state.setText("Paused"));stop.setOnAction(e->state.setText("Run stopped"));reset.setOnAction(e->state.setText("Ready to run"));
        VBox control=card(new VBox(15,section("Distance target","Set your next route goal"),new Spinner<Double>(.5,100,5,.5),new HBox(8,metres,miles),section("Run statistics","Live demo values"),stat("Distance","00.00 km"),stat("Elapsed time","00:00:00"),stat("Pace","--:--"),stat("Calories","0 kcal"),state,new HBox(8,start,pause,stop,reset)));control.setPrefWidth(330);return scroll(new VBox(20,title("Jogging tracker","Every run moves your rank forward."),new HBox(16,map,control)));
    }
    private Node gym(){HBox chips=new HBox(7);ToggleGroup group=new ToggleGroup();for(String m:List.of("Legs","Back","Biceps","Triceps","Chest")){ToggleButton b=chip(m,group);if(m.equals("Legs"))b.setSelected(true);chips.getChildren().add(b);}FlowPane cards=new FlowPane(14,14,workout("Barbell Squat","Foundational lower-body strength",4,8,"Intermediate"),workout("Romanian Deadlift","Hamstring and glute builder",3,10,"Intermediate"),workout("Walking Lunges","Single-leg endurance",3,12,"Beginner"));return scroll(new VBox(20,title("Gym recommender","Build a stronger character sheet."),section("Target muscle","Choose your focus"),chips,section("Workout recommendations","Legs · mock recommendations"),cards));}
    private Node reading(){timerLabel=new Label(format(seconds));timerLabel.getStyleClass().add("desktop-timer");Button start=primary("START"),pause=secondary("PAUSE"),reset=secondary("RESET");start.setOnAction(e->startTimer());pause.setOnAction(e->stopTimer());reset.setOnAction(e->{stopTimer();seconds=25*60;timerLabel.setText(format(seconds));});VBox focus=card(new VBox(16,section("Focus session","A calm, intentional reading sprint."),timerLabel,muted("Pomodoro reading timer"),new HBox(8,start,pause,reset)));focus.setAlignment(Pos.CENTER);HBox.setHgrow(focus,Priority.ALWAYS);VBox targets=card(new VBox(14,section("Reading targets","Mock values, editable in this UI."),new Label("Target duration"),new Slider(5,90,25),new Label("Target pages"),new Spinner<Integer>(1,250,20),section("Session history","Recent reading sessions"),history("Today","25 min · 18 pages","+55 XP"),history("Yesterday","40 min · 26 pages","+85 XP"),history("Sep 11","30 min · 21 pages","+60 XP")));targets.setPrefWidth(340);return scroll(new VBox(20,title("Reading session","Focus, learn, level up."),new HBox(16,focus,targets)));
    }
    private void startTimer(){if(timer==null){timer=new Timeline(new KeyFrame(Duration.seconds(1),e->{if(seconds>0){seconds--;timerLabel.setText(format(seconds));}else stopTimer();}));timer.setCycleCount(Timeline.INDEFINITE);}timer.play();}private void stopTimer(){if(timer!=null)timer.stop();}private String format(int s){return String.format("%02d:%02d",s/60,s%60);}
    private Node ranks(){HBox cards=new HBox(16,rank("🏃","JOGGING","GOLD",720,"Platinum",14,.72),rank("🏋","GYM","SILVER",430,"Gold",8,.43),rank("📖","READING","BRONZE",210,"Silver",5,.21));cards.getChildren().forEach(n->{HBox.setHgrow(n,Priority.ALWAYS);if(n instanceof Region r)r.setMaxWidth(Double.MAX_VALUE);});return scroll(new VBox(20,title("Maxxing ranks","Earn XP. Climb every tier."),cards,card(new VBox(8,new Label("RANK TIERS"),muted("Wood  ›  Bronze  ›  Silver  ›  Gold  ›  Platinum  ›  Diamond  ›  Champion  ›  Titan  ›  Olympian")))));}
    private VBox rank(String icon,String activity,String level,int xp,String next,int streak,double p){Label b=new Label(level);b.getStyleClass().add("rank-badge");VBox v=card(new VBox(13,new HBox(8,new Label(icon),new Label(activity),space(),b),new Label(level),bar(p),muted(xp+" / 1000 XP"),muted("Next rank: "+next),muted("🔥 "+streak+" day streak")));return v;}
    private Node settings(){ToggleButton dark=new ToggleButton("Dark Mode");dark.setSelected(theme.isDark());dark.getStyleClass().add("theme-toggle");dark.selectedProperty().addListener((o,old,v)->theme.setDark(v,root));VBox general=card(new VBox(14,section("Appearance","Customize your quest board."),row("Dark mode","Switch instantly between Primer themes",dark),row("Notifications","Quest reminders and streak nudges",new CheckBox()),row("Sound effects","Play subtle completion feedback",new CheckBox()),row("Compact cards","Fit more quests on screen",new CheckBox())));return scroll(new VBox(20,title("Settings","Tune the experience to your rhythm."),general));}
    private Node profile(){Label av=new Label("U");av.getStyleClass().add("desktop-avatar");VBox hero=card(new VBox(8,av,new Label("User"),muted("user@questlog.demo"),new Label("LEVEL 14  ·  GOLD RANK  ·  2,450 XP")));hero.setAlignment(Pos.CENTER);VBox info=card(new VBox(12,section("Profile settings","UI-only fields"),new Label("Display name"),new TextField("User"),new Label("Email"),new TextField("user@questlog.demo"),new Label("Current streak"),muted("🔥 12 days"),primary("SAVE PROFILE (DEMO)")));return scroll(new VBox(20,title("Profile","The adventurer behind the quests."),hero,info));}
    private VBox questRow(Quest q){Label icon=new Label(q.icon);icon.getStyleClass().add("quest-icon");Label name=new Label(q.name);name.getStyleClass().add("quest-name");Label status=badge(q.status,q.status.equals("DONE")?"status-complete":"status-active");ProgressBar p=bar(q.progress);HBox.setHgrow(p,Priority.ALWAYS);Button open=secondary("OPEN");open.setOnAction(e->open(q.category));return card(new HBox(12,icon,new VBox(4,name,muted(q.category),p),status,open));}
    private VBox workout(String name,String description,int sets,int reps,String difficulty){Button b=secondary("SELECT");b.setOnAction(e->b.setText("SELECTED"));VBox v=card(new VBox(10,new HBox(new Label(name),space(),badge(difficulty,"status-pending")),muted(description),new HBox(10,new VBox(4,muted("Sets"),new Spinner<Integer>(1,10,sets)),new VBox(4,muted("Reps"),new Spinner<Integer>(1,30,reps))),b));v.setPrefWidth(270);return v;}
    private HBox stat(String name,String value){Label v=new Label(value);v.getStyleClass().add("tracker-value");return new HBox(new VBox(2,muted(name),v),space());}private HBox history(String date,String data,String xp){return new HBox(new VBox(2,new Label(date),muted(data)),space(),muted(xp));}private HBox row(String a,String b,Node control){return new HBox(12,new VBox(2,new Label(a),muted(b)),space(),control);}private VBox activity(String date,String text,String xp){return new VBox(3,muted(date),new Label(text),muted(xp));}
    private VBox metric(String value,String label,String color){Label n=new Label(value);n.getStyleClass().addAll("desktop-stat",color);VBox box=card(new VBox(5,n,muted(label)));return box;}private VBox title(String a,String b){Label l=new Label(a);l.getStyleClass().add("page-greeting");return new VBox(3,l,muted(b));}private VBox section(String a,String b){Label l=new Label(a);l.getStyleClass().add("section-title");return new VBox(2,l,muted(b));}
    private VBox card(Node n){VBox b=new VBox(n);b.getStyleClass().add("questlog-card");return b;}private ScrollPane scroll(Node n){VBox w=new VBox(n);w.setPadding(new Insets(28));ScrollPane s=new ScrollPane(w);s.setFitToWidth(true);s.setHbarPolicy(ScrollPane.ScrollBarPolicy.NEVER);s.getStyleClass().add("content-scroll");return s;}private Button primary(String t){Button b=new Button(t);b.getStyleClass().add("questlog-button-primary");return b;}private Button secondary(String t){Button b=new Button(t);b.getStyleClass().add("questlog-button-secondary");return b;}private Label muted(String t){Label l=new Label(t);l.getStyleClass().add("muted-text");return l;}private Label badge(String t,String c){Label l=new Label(t);l.getStyleClass().addAll("status-badge",c);return l;}private ProgressBar bar(double v){ProgressBar p=new ProgressBar(v);p.setMaxWidth(Double.MAX_VALUE);p.getStyleClass().add("questlog-progress");return p;}private Region space(){Region r=new Region();HBox.setHgrow(r,Priority.ALWAYS);return r;}private ToggleButton chip(String t,ToggleGroup g){ToggleButton b=new ToggleButton(t);b.setToggleGroup(g);b.getStyleClass().add("filter-chip");return b;}private record Quest(String icon,String name,String category,double progress,String status){}
}
