package hobbytracker;

import java.sql.*;
import java.time.LocalDate;
import java.util.*;

/** JDBC-only persistence API. All callers run it on a background executor. */
public final class QuestDao {
    public Optional<User> findUser(String email) throws SQLException { return user("SELECT * FROM users WHERE LOWER(email)=LOWER(?)", email); }
    public Optional<String> passwordHashFor(long userId) throws SQLException { try(Connection c=DatabaseManager.connection(); PreparedStatement p=c.prepareStatement("SELECT password_hash FROM users WHERE id=?")){p.setLong(1,userId);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(r.getString(1)):Optional.empty();}} }
    public User createUser(String name, String email, String passwordHash) throws SQLException { try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement("INSERT INTO users(display_name,email,password_hash) VALUES(?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,name);p.setString(2,email);p.setString(3,passwordHash);p.executeUpdate();try(ResultSet keys=p.getGeneratedKeys()){if(!keys.next())throw new SQLException("User ID was not returned");return findUserById(keys.getLong(1)).orElseThrow();}} }
    public User updateUser(long id, String name, String email) throws SQLException { try(Connection c=DatabaseManager.connection(); PreparedStatement p=c.prepareStatement("UPDATE users SET display_name=?, email=? WHERE id=?")){p.setString(1,name);p.setString(2,email);p.setLong(3,id); if(p.executeUpdate()!=1)throw new SQLException("User no longer exists");} return findUserById(id).orElseThrow(); }
    public Optional<User> findUserById(long id) throws SQLException { return user("SELECT * FROM users WHERE id=?", id); }
    private Optional<User> user(String sql, Object v) throws SQLException { try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement(sql)){if(v instanceof Long l)p.setLong(1,l);else p.setString(1,(String)v);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(new User(r.getLong("id"),r.getString("display_name"),r.getString("email"),r.getInt("level"))):Optional.empty();}} }
    public List<Hobby> hobbies(long uid, boolean activeOnly) throws SQLException { String sql="SELECT * FROM hobbies WHERE user_id=?"+(activeOnly?" AND status='ACTIVE'":"")+" ORDER BY id DESC";List<Hobby>x=new ArrayList<>();try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement(sql)){p.setLong(1,uid);try(ResultSet r=p.executeQuery()){while(r.next())x.add(hobby(r));}}return x; }
    public Hobby addHobby(long uid,String title,String description) throws SQLException {try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement("INSERT INTO hobbies(user_id,title,description,status) VALUES(?,?,?,'ACTIVE')",Statement.RETURN_GENERATED_KEYS)){p.setLong(1,uid);p.setString(2,title);p.setString(3,description);p.executeUpdate();try(ResultSet k=p.getGeneratedKeys()){k.next();return byId(k.getLong(1));}}}
    public void updateProgress(long id,int progress) throws SQLException {try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement("UPDATE hobbies SET progress_percentage=?, status=CASE WHEN ? >= 100 THEN 'COMPLETED' ELSE status END WHERE id=?")){p.setInt(1,progress);p.setInt(2,progress);p.setLong(3,id);p.executeUpdate();}}
    public void complete(long id) throws SQLException {try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement("UPDATE hobbies SET status='COMPLETED',progress_percentage=100 WHERE id=?")){p.setLong(1,id);p.executeUpdate();}}
    public void log(long uid,String title,String description) throws SQLException {try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement("INSERT INTO activity_logs(user_id,action_title,action_description) VALUES(?,?,?)")){p.setLong(1,uid);p.setString(2,title);p.setString(3,description);p.executeUpdate();}}
    public List<String[]> recent(long uid,int limit) throws SQLException {List<String[]>x=new ArrayList<>();try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement("SELECT action_title,action_description,timestamp FROM activity_logs WHERE user_id=? ORDER BY timestamp DESC LIMIT ?")){p.setLong(1,uid);p.setInt(2,limit);try(ResultSet r=p.executeQuery()){while(r.next())x.add(new String[]{r.getTimestamp(3).toLocalDateTime().toLocalDate().toString(),r.getString(1),r.getString(2)});}}return x;}
    public Metrics metrics(long uid) throws SQLException {try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement("SELECT COALESCE(AVG(CASE WHEN status='ACTIVE' THEN progress_percentage END),0), COUNT(CASE WHEN status='ACTIVE' THEN 1 END), COUNT(CASE WHEN status='COMPLETED' THEN 1 END), COALESCE(MAX(streak_days),0) FROM hobbies WHERE user_id=?")){p.setLong(1,uid);try(ResultSet r=p.executeQuery()){r.next();return new Metrics(r.getDouble(1),r.getInt(2),r.getInt(3),r.getInt(4));}}}
    public int[] weeklyActivity(long uid) throws SQLException {int[]a=new int[7];try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement("SELECT DAYOFWEEK(timestamp),COUNT(*) FROM activity_logs WHERE user_id=? AND timestamp >= DATEADD('DAY',-6,CURRENT_TIMESTAMP) GROUP BY DAYOFWEEK(timestamp)")){p.setLong(1,uid);try(ResultSet r=p.executeQuery()){while(r.next())a[(r.getInt(1)+5)%7]=r.getInt(2);}}return a;}
    public String exportJson(long uid) throws SQLException {StringBuilder b=new StringBuilder("{\"hobbies\":[");for(Hobby h:hobbies(uid,false)){if(b.charAt(b.length()-1)!='[')b.append(',');b.append("{\"title\":\"").append(esc(h.title())).append("\",\"description\":\"").append(esc(h.description())).append("\",\"status\":\"").append(h.status()).append("\",\"progress\":").append(h.progressPercentage()).append('}');}return b.append("]}").toString();}
    private String esc(String x){return x==null?"":x.replace("\\","\\\\").replace("\"","\\\"");} private Hobby byId(long id)throws SQLException{try(Connection c=DatabaseManager.connection();PreparedStatement p=c.prepareStatement("SELECT * FROM hobbies WHERE id=?")){p.setLong(1,id);try(ResultSet r=p.executeQuery()){r.next();return hobby(r);}}} private Hobby hobby(ResultSet r)throws SQLException{return new Hobby(r.getLong("id"),r.getLong("user_id"),r.getString("title"),r.getString("description"),r.getString("status"),r.getInt("progress_percentage"),r.getInt("streak_days"));}
    public record Metrics(double overall,int active,int completed,int streak) { }
}
